### ISSUE TITLE
Does not work on password inputs

### ISSUE THREAD

**Issue by reednj** [phpinfo/MooTools-Placeholder#1]
When this is used on password elements you just get '*' character instead of the placeholder text.

The actual placeholder element works on password elements (in chrome anyway). Showing the placeholder text, but then showing the hidden '*' character when the user starts to type.

**Comment by phpinfo** [comment]
Thanks! I'll try to fix it soon.

**Comment by reednj** [comment]
I was going to submit a patch for it, but its harder than it seems... I was going to change the input type from password->text and back again. Works great in everything but IE, which won't let you change the type dynamically like that...
